from django.urls import path
from .views import (ContentionDetailView, HomeView,
                    ArgumentCreationView, PremiseCreationView,
                    PremiseDeleteView, ContentionJsonView,
                    PremiseEditView, ArgumentUpdateView,
                    ArgumentPublishView, ArgumentUnpublishView,
                    ArgumentDeleteView, AboutView, NewsView,
                    UpdatedArgumentsView, ReportView, RemoveReportView,
                    ControversialArgumentsView, TosView, SearchView,
                    NotificationsView, PremiseSupportView, PremiseUnsupportView,
                    StatsView, FallaciesView, FeaturedJSONView, NewsJSONView,
                    RandomArgumentView)


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    path('featured.json', FeaturedJSONView.as_view(), name='contentions_featured_json'),
    path('news.json', NewsJSONView.as_view(), name='contentions_latest_json'),
    path('news', NewsView.as_view(), name='contentions_latest'),
    path('search', SearchView.as_view(), name='contentions_search'),
    path('random', RandomArgumentView.as_view(), name='contentions_random'),
    path('updated', UpdatedArgumentsView.as_view(), name='contentions_updated'),
    path('controversial', ControversialArgumentsView.as_view(), name='contentions_controversial'),
    path('stats', StatsView.as_view(), name='contentions_stats'),
    path('fallacies', FallaciesView.as_view(), name='fallacies'),
    path('about', AboutView.as_view(), name='about'),
    path('tos', TosView.as_view(), name='tos'),
    path('new-argument', ArgumentCreationView.as_view(), name='new_argument'),
    path('<slug:slug>/edit', ArgumentUpdateView.as_view(), name='contention_edit'),
    path('<slug:slug>.json', ContentionJsonView.as_view(), name='contention_detail_json'),
    path('<slug:slug>', ContentionDetailView.as_view(), name='contention_detail'),
    path('<slug:slug>/<int:premise_id>', ContentionDetailView.as_view(), name='premise_detail'),
    path('<slug:slug>/premises/<int:pk>/unsupport', PremiseUnsupportView.as_view(), name='unsupport_premise'),
    path('<slug:slug>/premises/<int:pk>/support', PremiseSupportView.as_view(), name='support_premise'),
    path('<slug:slug>/premises/<int:pk>/delete', PremiseDeleteView.as_view(), name='delete_premise'),
    path('<slug:slug>/premises/<int:pk>/report', ReportView.as_view(), name='report_premise'),
    path('<slug:slug>/premises/<int:pk>/unreport', RemoveReportView.as_view(), name='unreport_premise'),
    path('<slug:slug>/premises/<int:pk>/new', PremiseCreationView.as_view(), name='insert_premise'),
    path('<slug:slug>/premises/<int:pk>', PremiseEditView.as_view(), name='edit_premise'),
    path('<slug:slug>/premises/new', PremiseCreationView.as_view(), name='new_premise'),
    path('<slug:slug>/publish', ArgumentPublishView.as_view(), name='contention_publish'),
    path('<slug:slug>/unpublish', ArgumentUnpublishView.as_view(), name='contention_unpublish'),
    path('<slug:slug>/delete', ArgumentDeleteView.as_view(), name='contention_delete'),
]
