# Generated by Django 3.2.7 on 2021-09-10 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premises', '0001_initial'),
        ('nouns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premise',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='premises.contention'),
        ),
        migrations.AddField(
            model_name='premise',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="The parent of premise. If you don't choose anything, it will be a main premise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='premises.premise', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='premise',
            name='related_argument',
            field=models.ForeignKey(blank=True, help_text='You can also associate your premise with an argument.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_premises', to='premises.contention', verbose_name='Related Argument'),
        ),
        migrations.AddField(
            model_name='premise',
            name='supporters',
            field=models.ManyToManyField(related_name='supporting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_premises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contention',
            name='nouns',
            field=models.ManyToManyField(blank=True, null=True, related_name='contentions', to='nouns.Noun'),
        ),
        migrations.AddField(
            model_name='contention',
            name='related_nouns',
            field=models.ManyToManyField(blank=True, null=True, related_name='contentions_related', to='nouns.Noun'),
        ),
        migrations.AddField(
            model_name='contention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to=settings.AUTH_USER_MODEL),
        ),
    ]
