# Generated by Django 3.2.7 on 2021-09-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nouns', '0003_auto_20210913_0616'),
        ('premises', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contention',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contention',
            name='language',
            field=models.CharField(choices=[('tr', 'tr')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contention',
            name='nouns',
            field=models.ManyToManyField(blank=True, related_name='contentions', to='nouns.Noun'),
        ),
        migrations.AlterField(
            model_name='contention',
            name='related_nouns',
            field=models.ManyToManyField(blank=True, related_name='contentions_related', to='nouns.Noun'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='premises.contention'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='premises.premise'),
        ),
    ]
